version: '3'

services:
  php:
    image: php:7.1-fpm
    expose:
      - 9000
    volumes:
      - ./app:/var/www/html
    networks:
      - local-network
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    networks:
      - local-network

networks:
  local-network:
    external: true
